# Generated by Django 3.2.16 on 2023-06-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desription',
            new_name='description',
        ),
    ]
